### ISSUE TITLE
please add support for arm64

### ISSUE THREAD

**Issue by e1ke** [burritosoftware/Outline-Authentik-Connector#1]
Hi,
I just encountered your python script with Docker-Container and it runs great on my linux/amd64 server.
However, i have multiple servers running arm64 architecture and sadly your Docker-Image 
https://hub.docker.com/r/burritosoftware/outline-authentik-connector
is not prepared for that.
On starting the docker container, the typical error msg appears, when running amd64 images on arm64:

`exec /usr/local/bin/fastapi: exec format error`

Of course I could install it manually and run it (great documentation btw), but that would destry my portainer / docker tidiness
Thanks in advance

**Comment by burritosoftware** [comment]
I’ll see if I can have GitHub Actions create an ARM-ready image. I’m just about to start college however, so I can’t guarantee I can get around to it—a PR for this with a tested image would be appreciated!

**Comment by burritosoftware** [comment]
@e1ke I have now pushed an arm64-compatible Docker image to Docker Hub and ghcr.io: this is untested but should work the same way, please let me know if there's any issues!

**Comment by e1ke** [comment]
@burritosoftware thank you very much! I will test it soon if it works on my Hetzner arm64 server.

**Comment by e1ke** [comment]
I tested the image from docker hub with tag 'master', which supports linux/arm64 (yay), but i ran into the following issue right at the beginning when i start the container:

```
Traceback (most recent call last):
  File "/usr/local/bin/fastapi", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/cli.py", line 12, in main
    raise RuntimeError(message)  # noqa: B904
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: To use the fastapi command, please install "fastapi[standard]":
	pip install "fastapi[standard]"
To use the fastapi command, please install "fastapi[standard]":
	pip install "fastapi[standard]"
```

it seems, that fastapi is not preinstalled in this image?

**Comment by burritosoftware** [comment]
I will see if I need to add that requirement of `[standard]` as the Docker image does use the `fastapi` command to run the script. Thanks for the heads up!

**Comment by burritosoftware** [comment]
@e1ke I pushed a brand new build to tag `master`, please check if it's good! If it is, then I will be creating new release 1.0.2 and pushing to `latest` tag instead.

**Comment by e1ke** [comment]
@burritosoftware I just checked quickly via phone because I am in bed but it's looking great. Running with the INFOs
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)

Thanks mate! Good work

**Comment by burritosoftware** [comment]
Awesome, thank you! Will now be pushing version 1.0.2 to latest.
